# Generated by Django 4.0.3 on 2022-03-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotmap', '0004_item_id_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_itemcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Item Code'),
        ),
    ]
