# Generated by Django 4.0.3 on 2022-04-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotmap', '0005_alter_item_id_itemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=200, null=True, verbose_name='Item Description')),
                ('location', models.CharField(max_length=50, null=True, verbose_name='Location')),
                ('item_live_location_source', models.CharField(max_length=40, null=True, verbose_name='Item Live Location Source')),
                ('last_updation', models.DateField(null=True, verbose_name='Last Updation')),
                ('departmentContactDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plotmap.departmentcontactdetails')),
            ],
        ),
    ]
